# Pre-Procesamiento de Datos

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split

Una vista al dataset:

In [16]:
# Leemos el dataset
df = pd.read_csv(
    'Crimes_-_2015_20260905.csv',
    parse_dates=['Date', 'Updated On'],
    date_format={
        'Date': '%m/%d/%Y %I:%M:%S %p',
        'Updated On': "%Y %b %d %I:%M:%S %p",
    },
)

df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10365064,HZ100370,12/31/2015 11:59:00 PM,075XX S EMERALD AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,17.0,68.0,14,1172605.0,1854931.0,2015,2018 Feb 10 03:50:01 PM,41.757367,-87.642993,POINT (-87.642992854 41.757366519)
1,10460641,HZ199559,12/31/2015 11:59:00 PM,015XX N KEDZIE AVE,0890,THEFT,FROM BUILDING,RESIDENCE PORCH/HALLWAY,False,False,...,26.0,23.0,06,NaN,NaN,2015,2018 Feb 09 03:44:29 PM,NaN,NaN,NaN
2,10364662,HZ100006,12/31/2015 11:55:00 PM,079XX S STONY ISLAND AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,False,False,...,8.0,45.0,04B,1188223.0,1852840.0,2015,2018 Feb 10 03:50:01 PM,41.751270,-87.585822,POINT (-87.585822373 41.751270452)
3,10364740,HZ100010,12/31/2015 11:50:00 PM,024XX W FARGO AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,50.0,2.0,06,1158878.0,1949369.0,2015,2018 Feb 10 03:50:01 PM,42.016804,-87.690709,POINT (-87.690708662 42.016804165)
4,10364683,HZ100002,12/31/2015 11:50:00 PM,037XX N CLARK ST,0460,BATTERY,SIMPLE,SIDEWALK,True,False,...,44.0,6.0,08B,1167786.0,1925033.0,2015,2018 Feb 10 03:50:01 PM,41.949837,-87.658635,POINT (-87.658635101 41.949837364)

Vamos a investigar crímenes que aparecen duplicados en el dataset.

In [17]:
df_duplicates = df[df.duplicated(subset=['Case Number'], keep=False)]
df_unique = df.drop_duplicates(subset=['Case Number'], keep='first')

df_duplicates.head(20)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
2840,22240,HY551250,12/27/2015 06:05:00 AM,059XX S WENTWORTH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,20.0,68.0,01A,1175978.0,1865746.0,2015,2022 Sep 19 03:41:05 PM,41.786969,-87.630307,POINT (-87.630307356 41.786969136)
2910,22239,HY551250,12/27/2015 02:16:00 AM,059XX S WENTWORTH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,20.0,68.0,01A,1175978.0,1865746.0,2015,2022 Sep 19 03:41:05 PM,41.786969,-87.630307,POINT (-87.630307356 41.786969136)
66152,22127,HY442430,09/29/2015 03:35:00 AM,003XX W 42ND ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,3.0,37.0,01A,1174451.0,1877100.0,2015,2022 Sep 01 03:42:17 PM,41.818160,-87.635568,POINT (-87.635568188 41.818159764)
66177,22125,HY442430,09/29/2015 01:45:00 AM,003XX W 42ND ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,3.0,37.0,01A,1174451.0,1877100.0,2015,2022 Sep 01 03:42:17 PM,41.818160,-87.635568,POINT (-87.635568188 41.818159764)
66188,22126,HY442430,09/29/2015 01:05:00 AM,003XX W 42ND ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,3.0,37.0,01A,1174451.0,1877100.0,2015,2022 Sep 01 03:42:17 PM,41.818160,-87.635568,POINT (-87.635568188 41.818159764)
66379,22122,HY442160,09/28/2015 08:10:00 PM,053XX S ABERDEEN ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,16.0,61.0,01A,1169890.0,1869399.0,2015,2022 Sep 01 03:42:17 PM,41.797128,-87.652523,POINT (-87.652523151 41.797127818)
66380,22123,HY442160,09/28/2015 08:08:00 PM,053XX S ABERDEEN ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,16.0,61.0,01A,1169890.0,1869399.0,2015,2022 Sep 01 03:42:17 PM,41.797128,-87.652523,POINT (-87.652523151 41.797127818)
86976,22069,HY406845,09/02/2015 02:55:00 AM,050XX N WINTHROP AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,48.0,3.0,01A,1167957.0,1933812.0,2015,2022 Sep 19 03:41:05 PM,41.973924,-87.657752,POINT (-87.657752098 41.973923557)
86980,22068,HY406845,09/02/2015 02:41:00 AM,050XX N WINTHROP AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,48.0,3.0,01A,1167957.0,1933812.0,2015,2022 Sep 19 03:41:05 PM,41.973924,-87.657752,POINT (-87.657752098 41.973923557)
90101,22216,HY402004,08/29/2015 09:42:00 AM,052XX S LOREL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,False,False,...,23.0,56.0,01A,1141580.0,1869447.0,2015,2022 Sep 19 03:41:05 PM,41.797828,-87.756340,POINT (-87.756339623 41.797827897)
90102,22217,HY402004,08/29/2015 09:42:00 AM,052XX S LOREL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,False,False,...,23.0,56.0,01A,1141580.0,1869447.0,2015,2022 Sep 19 03:41:05 PM,41.797828,-87.756340,POINT (-87.756339623 41.797827897)
92337,22057,HY397947,08/26/2015 02:07:00 PM,030XX W VAN BUREN ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,28.0,27.0,01A,1155960.0,1898002.0,2015,2022 Sep 19 03:41:05 PM,41.875909,-87.702837,POINT (-87.702836558 41.875909279)
92446,22056,HY397947,08/26/2015 11:37:00 AM,030XX W VAN BUREN ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,28.0,27.0,01A,1155960.0,1898002.0,2015,2022 Sep 19 03:41:05 PM,41.875909,-87.702837,POINT (-87.702836558 41.875909279)
99402,22039,HY385366,08/17/2015 04:08:00 PM,016XX S SPRINGFIELD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,24.0,29.0,01A,1150669.0,1891448.0,2015,2022 Sep 19 03:41:05 PM,41.858029,-87.722435,POINT (-87.722434585 41.858029356)
99890,22036,HY385366,08/16/2015 10:26:00 PM,016XX S SPRINGFIELD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,24.0,29.0,01A,1150669.0,1891448.0,2015,2022 Sep 19 03:41:05 PM,41.858029,-87.722435,POINT (-87.722434585 41.858029356)
108095,22021,HY371882,08/06/2015 07:43:00 PM,109XX S PARNELL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,21.0,49.0,01A,1174576.0,1832444.0,2015,2025 Dec 02 03:42:14 PM,41.695616,-87.636437,POINT (-87.636436642 41.695615506)
108141,22020,HY371882,08/06/2015 06:52:00 PM,109XX S PARNELL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,21.0,49.0,01A,1174576.0,1832444.0,2015,2025 Dec 02 03:42:14 PM,41.695616,-87.636437,POINT (-87.636436642 41.695615506)
117466,21996,HY355926,07/26/2015 02:34:00 AM,006XX N AVERS AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,True,False,...,27.0,23.0,01A,1150608.0,1904047.0,2015,2022 Sep 19 03:41:05 PM,41.892604,-87.722329,POINT (-87.722329283 41.892603612)
117467,21997,HY355926,07/26/2015 02:34:00 AM,006XX N AVERS AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,True,False,...,27.0,23.0,01A,1150608.0,1904047.0,2015,2022 Sep 01 03:42:17 PM,41.892604,-87.722329,POINT (-87.722329283 41.892603612)
124277,21984,HY344710,07/17/2015 05:23:00 PM,046XX N KOSTNER AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,45.0,16.0,01A,1146003.0,1930488.0,2015,2022 Sep 01 03:42:17 PM,41.965249,-87.738568,POINT (-87.73856815 41.965248952)

In [18]:
# Algunos crímenes aparecen más de una vez en el dataset, asi que los identificamos a través del Case Number
df_unique = df.drop_duplicates('Case Number')

# Definimos nuestra variable objectivo
y = df_unique['Arrest']

# Eliminamos las variables redundantes para dejar solo los features
X = df_unique.drop([
    # Variable objetivo
    'Arrest',

    # Identificadores
    'ID',
    'Case Number',

    # Fue asignado posterior al hecho
    'Updated On',

    # Tiene el mismo valor para todas las filas
    'Year',

    # Redundantes con respecto a X Coordinate y Y Coordinate
    'Latitude',
    'Longitude',
    'Location',
], axis=1)

X.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate
0,12/31/2015 11:59:00 PM,075XX S EMERALD AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,621,6,17.0,68.0,14,1172605.0,1854931.0
1,12/31/2015 11:59:00 PM,015XX N KEDZIE AVE,0890,THEFT,FROM BUILDING,RESIDENCE PORCH/HALLWAY,False,1422,14,26.0,23.0,06,NaN,NaN
2,12/31/2015 11:55:00 PM,079XX S STONY ISLAND AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,False,411,4,8.0,45.0,04B,1188223.0,1852840.0
3,12/31/2015 11:50:00 PM,024XX W FARGO AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,2411,24,50.0,2.0,06,1158878.0,1949369.0
4,12/31/2015 11:50:00 PM,037XX N CLARK ST,0460,BATTERY,SIMPLE,SIDEWALK,False,1923,19,44.0,6.0,08B,1167786.0,1925033.0

In [19]:
# Realizamos los splits de train y test
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
)

print(str(len(X_train.index))+' filas de train')
print(str(len(X_test.index))+' filas de test')

211906 filas de train
52977 filas de test