In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
# Leemos el dataset
df = pd.read_csv(
    'Crimes_-_2015_20260905.csv',
    parse_dates=['Date', 'Updated On'],
    date_format={
        'Date': '%m/%d/%Y %I:%M:%S %p',
        'Updated On': "%Y %b %d %I:%M:%S %p",
    },
)

df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10365064,HZ100370,2015-12-31 23:59:00,075XX S EMERALD AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,17.0,68.0,14,1172605.0,1854931.0,2015,2018-02-10 15:50:01,41.757367,-87.642993,POINT (-87.642992854 41.757366519)
1,10460641,HZ199559,2015-12-31 23:59:00,015XX N KEDZIE AVE,0890,THEFT,FROM BUILDING,RESIDENCE PORCH/HALLWAY,False,False,...,26.0,23.0,06,NaN,NaN,2015,2018-02-09 15:44:29,NaN,NaN,NaN
2,10364662,HZ100006,2015-12-31 23:55:00,079XX S STONY ISLAND AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,False,False,...,8.0,45.0,04B,1188223.0,1852840.0,2015,2018-02-10 15:50:01,41.751270,-87.585822,POINT (-87.585822373 41.751270452)
3,10364740,HZ100010,2015-12-31 23:50:00,024XX W FARGO AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,50.0,2.0,06,1158878.0,1949369.0,2015,2018-02-10 15:50:01,42.016804,-87.690709,POINT (-87.690708662 42.016804165)
4,10364683,HZ100002,2015-12-31 23:50:00,037XX N CLARK ST,0460,BATTERY,SIMPLE,SIDEWALK,True,False,...,44.0,6.0,08B,1167786.0,1925033.0,2015,2018-02-10 15:50:01,41.949837,-87.658635,POINT (-87.658635101 41.949837364)

In [4]:
# Algunos crímenes aparecen más de una vez en el dataset, asi que los identificamos a través del Case Number
df_unique = df.drop_duplicates('Case Number')

# Definimos nuestra variable objectivo
y = df_unique['Arrest']

# Eliminamos las variables redundantes para dejar solo los features
X = df_unique.drop([
    # Variable objetivo
    'Arrest',
    
    # Identificadores
    'ID',
    'Case Number',

    # Fue asignado posterior al hecho
    'Updated On',

    # Tiene el mismo valor para todas las filas
    'Year',

    # Redundantes con respecto a X Coordinate y Y Coordinate
    'Latitude',
    'Longitude',
    'Location',
], axis=1)

X.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate
0,2015-12-31 23:59:00,075XX S EMERALD AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,621,6,17.0,68.0,14,1172605.0,1854931.0
1,2015-12-31 23:59:00,015XX N KEDZIE AVE,0890,THEFT,FROM BUILDING,RESIDENCE PORCH/HALLWAY,False,1422,14,26.0,23.0,06,NaN,NaN
2,2015-12-31 23:55:00,079XX S STONY ISLAND AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,False,411,4,8.0,45.0,04B,1188223.0,1852840.0
3,2015-12-31 23:50:00,024XX W FARGO AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,2411,24,50.0,2.0,06,1158878.0,1949369.0
4,2015-12-31 23:50:00,037XX N CLARK ST,0460,BATTERY,SIMPLE,SIDEWALK,False,1923,19,44.0,6.0,08B,1167786.0,1925033.0

In [5]:
# Realizamos los splits de train y test
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
)

print(str(len(X_train.index))+' filas de train')
print(str(len(X_test.index))+' filas de test')

211906 filas de train
52977 filas de test